version: '2'
services:
  app:
    container_name: app-rails
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile.dev
    ports:
      - '80:80'
    volumes:
      - ~/git/github/food-sharing-portfolio:/var/www/app/
    tty: true
    depends_on:
      - db
  db:
    container_name: mysql-57
    build: 
      context: .
      dockerfile: ./docker/dev/mysql/Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_HOST: $MYSQL_DOCKER_HOST
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/dev/mysql/db_data:/var/lib/mysql