version: '2'
services:
  app:
    container_name: app-rails
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile.dev
    environment:
      RAILS_ENV: development
    env_file: .env
    # ports番号の前者はホストからappコンテナにアクセスする際のポート番号（localhost:8080）
    # ports番号の後者はdockerネットワーク内でのアクセスポートとなる（関係するのはdbコンテナ）
    ports:
      - '8080:80'
    # バインドマウントにより、food-sharing-portfolioのコードをコンテナ内にする
    volumes:
      - ~/git/github/food-sharing-portfolio:/var/www/app/
    tty: true
    depends_on:
      - db
  db:
    container_name: mysql-57
    build: 
      context: .
      dockerfile: ./docker/dev/mysql/Dockerfile.dev
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # ports番号の前者はホストからのアクセスポート、後者はdockerネットワーク内（appコンテナと同じネットワーク）でのアクセスポート
    # 3306はdatabase.ymlのdevelopment環境のポート番号と一致させること
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: food_share_app_database_dev
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/dev/mysql/db_data:/var/lib/mysql