FROM ruby:2.6.6
ENV APP_ROOT /var/www/app
WORKDIR $APP_ROOT

RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN touch /tmp/mysql.sock
RUN chmod 777 /tmp/mysql.sock
ADD ./docker/dev/mysql/mysql.cnf /etc/mysql/mysql.cnf

# unicorn.rbのソケットとプロセスIDを格納するフォルダを権限付きで作成する。unixドメインソケットで通信するため
RUN mkdir -p /var/www/app/tmp/sockets
RUN chmod -R 755 /var/www/app/tmp/sockets
RUN mkdir -p /var/www/app/tmp/pids
RUN chmod -R 755 /var/www/app/tmp/pids

# dockerfileの推奨はapt-getで実行ファイルをインストール
# apt-get updateとapt-get upgrade、apt-get install -y は&&で繋げないとキャッシュ問題などでエラーが出る。「RUN apt-get update && apt-get install -y」が推奨
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    sudo \
    curl \
    git \
    default-mysql-client \
    locales \
    sudo \
    libpq-dev \
    nodejs \
    vim \
    nginx \
    supervisor \
    nodejs \
    yarn \
    zlib1g-dev && \
    apt-get clean -y && \
    # apt-getでインストールした実行ファイルのキャッシュを削除して、コンテナを軽くする
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

# setting locales
RUN localedef -f UTF-8 -i en_US en_US.UTF-8

# Setup UTC+9
RUN cp -p /etc/localtime /etc/localtime.UTC \
    && cp -p /usr/share/zoneinfo/Japan /etc/localtime

ADD ./Gemfile $APP_ROOT/Gemfile
ADD ./Gemfile.lock $APP_ROOT/Gemfile.lock
# bundle install
RUN gem install bundler -v 1.17.3 && bundle install

# yarn install Preparation
RUN npm install n -g
RUN n 12.18.4

##nginx
RUN groupadd nginx
RUN useradd -g nginx nginx
# 圧縮ファイルを解凍してコピーしたい時はADDを使う
ADD ./docker/dev/app/nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./docker/dev/app/nginx/dev.defalut.conf /etc/nginx/conf.d/defalut.conf

##supervisor
RUN mkdir -p /var/log/supervisor
ADD ./docker/dev/app/supervisor/dev.app.conf /etc/supervisor/conf.d/app.conf

EXPOSE 80
CMD ["/usr/bin/supervisord"]
